EOS                                    -- Generated : Petrel
  PR /

PRCORR                                 -- Generated : Petrel

CNAMES                                 -- Generated : Petrel
  C1 CO2 /

TCRIT                                  -- Generated : Petrel
  190.6 304.7 /

PCRIT                                  -- Generated : Petrel
  46.0421 73.8659 /

VCRIT                                  -- Generated : Petrel
  0.098 0.094 /

ZCRIT                                  -- Generated : Petrel
  0.284724 0.274072 /

VCRITVIS                               -- Generated : Petrel
  0.098 0.094 /

ZCRITVIS                               -- Generated : Petrel
  0.284724 0.274072 /

MW                                     -- Generated : Petrel
  16.043 44.01 /

ACF                                    -- Generated : Petrel
  0.013 0.225 /

OMEGAA                                 -- Generated : Petrel
  2*0.457235529 /

OMEGAB                                 -- Generated : Petrel
  2*0.077796074 /

SSHIFT                                 -- Generated : Petrel
  -0.1486264 -0.04958 /

BIC                                    -- Generated : Petrel
  0.12 /

PARACHOR                               -- Generated : Petrel
  77 78 /

