-- Eaq = 5.71e+05 bar
-- Cmaq = 1.46e-06 1/bar
-- nuaq = 2.50e-01
-- poroaq = 2.00e-01
-- Cpaq = 7.30e-06 bar

-- Ecap = 5.71e+05 bar
-- Cmcap = 1.46e-06 1/bar
-- nuca = 2.50e-01
-- porocap = 1.00e-01
-- Cpcap = 1.46e-05 bar

--rocknum=1 -> caprock+outside
--rocknum=2 -> aquifer

ROCK
150.0  1.46e-05 /
150.0  7.30e-06 /


--GROCK
--0.0  3.807e+05  0.200000 /
--0.0  3.807e+05  0.200000 /

